# Generated by Django 5.0.7 on 2026-06-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveorder',
            name='exception_status',
            field=models.CharField(choices=[('none', '无异常'), ('open', '异常未关闭'), ('closed', '异常已关闭')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='moveorder',
            name='settlement_status',
            field=models.CharField(choices=[('pending', '结算待确认'), ('confirmed', '结算已确认')], default='pending', max_length=20),
        ),
    ]
