# Generated by Django 5.0.7 on 2026-06-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
