# Generated by Django 5.0.7 on 2026-06-19 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_moveorder_exception_status_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicereview',
            options={'ordering': ['-created_at', '-version']},
        ),
        migrations.AddField(
            model_name='servicereview',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews', to='orders.moveorder'),
        ),
        migrations.AlterUniqueTogether(
            name='servicereview',
            unique_together={('order', 'version')},
        ),
    ]
